databases:
  - name: companion-db
    databaseName: websitecompanion
    user: companion
    plan: free

services:
  - type: web
    name: genius-api
    env: python
    rootDir: genius-framework
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_production:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: genius-framework
      - key: OPENAI_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://websitecompanion.ai,https://app.websitecompanion.ai,https://companion-viewer.onrender.com
