databases:
  - name: typebot-db
    databaseName: typebot
    user: typebot
    plan: free

services:
  - type: web
    name: typebot-viewer
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: typebot-db
          property: connectionString
      - key: ENCRYPTION_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://typebot-viewer.onrender.com
      - key: NEXT_PUBLIC_VIEWER_URL
        value: https://typebot-viewer.onrender.com
        
  - type: web
    name: genius-api
    env: python
    rootDir: genius-framework
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_production:app"
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: genius-framework
      - key: OPENAI_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://typebot-viewer.onrender.com,https://rtrvehicles.com
