databases:
  - name: companion-db
    databaseName: websitecompanion
    user: companion
    plan: free

services:
  - type: web
    name: website-companion-viewer
    env: docker
    image: "baptistearno/typebot:latest"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: companion-db
          property: connectionString
      - key: ENCRYPTION_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://websitecompanion.ai
      - key: NEXT_PUBLIC_VIEWER_URL
        value: https://websitecompanion.ai

  - type: web
    name: genius-api
    env: python
    rootDir: genius-framework
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_production:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: genius-framework
      - key: OPENAI_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://websitecompanion.ai,https://api.websitecompanion.ai
