databases:
  - name: companion-db
    databaseName: websitecompanion
    user: companion
    plan: free

services:
  - type: web
    name: genius-api
    env: python
    rootDir: genius-framework
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_production:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: genius-framework
      - key: OPENAI_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://websitecompanion.ai,https://app.websitecompanion.ai,https://typebot-complete.onrender.com

  - type: web
    name: typebot-complete
    env: docker
    image: baptistearno/typebot-viewer:latest
    envVars:
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        fromDatabase:
          name: companion-db
          property: connectionString
      - key: NEXT_PUBLIC_VIEWER_URL
        value: https://typebot-complete.onrender.com
      - key: NEXTAUTH_URL
        value: https://typebot-complete.onrender.com
      - key: ENCRYPTION_SECRET
        generateValue: true
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET
        value: web-companion-genesis
      - key: S3_REGION
        value: us-east-2
      - key: S3_ENDPOINT
        value: https://s3.us-east-2.amazonaws.com
      - key: NEXT_PUBLIC_S3_BUCKET
        value: web-companion-genesis
      - key: NEXT_PUBLIC_S3_REGION
        value: us-east-2
      - key: NEXT_PUBLIC_S3_ENDPOINT
        value: https://s3.us-east-2.amazonaws.com
