databases:
  - name: companion-db
    databaseName: websitecompanion
    user: companion
    plan: free

services:
  - type: web
    name: genius-api
    env: python
    rootDir: genius-framework
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_production:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: genius-framework
      - key: OPENAI_API_KEY
        sync: false
      - key: GENIUS_API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://websitecompanion.ai,https://app.websitecompanion.ai,https://typebot-complete.onrender.com

- type: web
    name: typebot-complete
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: ""
    buildCommand: "docker build --build-arg SCOPE=viewer -f Dockerfile ."
    envVars:
      - fromGroup: typebot-shared
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
      - key: SKIP_MIGRATIONS
        value: "true"
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/typebot
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET
        value: web-companion-genesis
      - key: S3_REGION
        value: us-east-2
      - key: S3_ENDPOINT
        value: https://s3.us-east-2.amazonaws.com
      - key: NEXT_PUBLIC_S3_BUCKET
        value: web-companion-genesis
      - key: NEXT_PUBLIC_S3_REGION
        value: us-east-2
      - key: NEXT_PUBLIC_S3_ENDPOINT
        value: https://s3.us-east-2.amazonaws.com
